import Performance from './pages/Performance';

// ...existing code...
<Routes>
  // ...existing routes...
  <Route path="/performance" element={<Performance />} />
  // ...existing routes...
</Routes>
// ...existing code...
